<?php

use Illuminate\Database\Seeder;

class MemberTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'first_name' =>'Bùi Thu Hà',
                'last_name' => 'Phí',
                'mobile' =>'0975896799',
                'company_name' => 'Vng media',
                'position' =>'Phó giám đốc',
                'career' => 'Truyền thông ',
                'email' =>'Nguyenha@vngmedia.vn',
                'fb_url' => 'Phí Bùi Thu Hà',
                'company_website' => 'Vnggroup.com.vn',
                'bio' =>'Chuyên viết bài, xây dựng chiến lược truyền thông,kết
                    bối báo chí và tổ chức sự kiện nhất là lĩnh vc bds.
                    Là phóng viên BĐS kỳ cựu trong giới báo chí',
                'security_question1' =>'19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => 'Kết nối và học hỏi',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>' Xuân Thủy',
                'last_name' => 'Nguyễn',
                'mobile' =>'0942751982/0973993463',
                'company_name' => 'Công ty CP Giao nhận Việt Bill',
                'position' =>'Giám đốc',
                'career' => 'Logistic (vận tải và tt Hải quan)',
                'email' =>'Xuanthuyvietbill@gmail.com',
                'fb_url' => 'Thuy Nguyen Xuan',
                'company_website' => '',
                'bio' =>'Chúng tôi đã hoạt động trong lĩnh vực giao nhận vận
                    tải và thủ tục hải quan (logistic) gần 10 năm. Đối với chúng
                    tôi không có lô hàng nào bị cho là bé và cũng không có có lô hàng ',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Đỗ văn Thạch',
                'wanted' => 'Hợp tác, học hỏi, giao lưu và chia sẻ cơ hội, kiến thức...',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Hồng Vân',
                'last_name' => 'Lê',
                'mobile' =>'0988889786',
                'company_name' => 'CT CP ĐT VĨNH CÁT ',
                'position' =>'Trưởng phòng',
                'career' => 'Xuất khẩu lao động ',
                'email' =>'Levan.xkld@gmail.com',
                'fb_url' => 'Levan.xkld@gmai.com',
                'company_website' => '',
                'bio' =>'Mạnh mẽ, quyết đoán , trung thực ',
                'security_question1' =>'18/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => 'Mở rộng quan hệ , học hỏi những điều mới lạ từ các bạn để có thêm kinh nghiệm ',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Minh Cừ',
                'last_name' => 'Hoàng',
                'mobile' =>'0983360777',
                'company_name' => 'Công ty TNHHXD&TM Hoàng Dũng',
                'position' =>'Giám đốc',
                'career' => 'Sản xuất cọc bê tông , ép cọc bê tông, cẩu vận tải HH',
                'email' =>'cpcochoangdung.tn74@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Hoàng Lân',
                'last_name' => 'Trần',
                'mobile' =>'0948338899',
                'company_name' => 'Luật Trần Gia',
                'position' =>'Giám đốc',
                'career' => 'Luật',
                'email' =>'Tranhoanglan14@yahoo.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Mạnh Hùng',
                'last_name' => 'Nguyễn',
                'mobile' =>'0972105241',
                'company_name' => 'CHUBB Life',
                'position' =>'',
                'career' => 'Bảo Hiểm Nhân Thọ',
                'email' =>'manhhungnts@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thị Lan Anh',
                'last_name' => 'Vũ',
                'mobile' =>'01656931848',
                'company_name' => 'CT TNHH Đào tạo Tư vấn PDCA',
                'position' =>'',
                'career' => 'Đào tạo',
                'email' =>'lananh.pdca@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Vũ Việt',
                'last_name' => 'Nguyễn',
                'mobile' =>'0912682359',
                'company_name' => 'Olife Co.,ltd',
                'position' =>'',
                'career' => 'www.banhmivietan.com & www.queminh.vn',
                'email' =>'vietnguyenvu@gmail.com',
                'fb_url' => '',
                'company_website' => 'www.banhmivietan.com',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Đình Tứ',
                'last_name' => 'Hoàng',
                'mobile' =>'0967891252',
                'company_name' => 'Xưởng nhôm kính trường thịnh',
                'position' =>'',
                'career' => 'Gia công nhôm kính',
                'email' =>'Hoangdinhtu2658@gmai.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Văn Bảo',
                'last_name' => 'Lê',
                'mobile' =>'0979419419',
                'company_name' => 'Công ty Cp tư vấn TK XD TM Lê Bảo',
                'position' =>'',
                'career' => 'Xây Dựng',
                'email' =>'Lebaoxd@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'ngọc san',
                'last_name' => 'Đào',
                'mobile' =>'0981116342',
                'company_name' => 'Công ty TNHH dịch vụ thương mại đào gia',
                'position' =>'',
                'career' => 'Bán và cho thuê máy photocopy',
                'email' =>'Sandaogia@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thanh Hiền',
                'last_name' => 'Lê',
                'mobile' =>'0983318889',
                'company_name' => 'Công ty cổ phần đầu tư Meikoh Việt Nam',
                'position' =>'',
                'career' => 'Sản xuất Sơn tường & bột bat',
                'email' =>'Lehienvid@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Bá Hòa',
                'last_name' => 'Nguyễn',
                'mobile' =>'0919935065',
                'company_name' => 'Công ty cổ phần đầu tư phát triển Hòa Tiến',
                'position' =>'',
                'career' => 'Sắt thép, vật liệu xd.',
                'email' =>'Bahoa.vn@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Hải Nam',
                'last_name' => 'Lê',
                'mobile' =>'0912609760',
                'company_name' => 'Công ty CP Thượng Long',
                'position' =>'Chủ tịch HĐQT',
                'career' => 'Bê tông thương phẩm- Gạch không nung',
                'email' =>'lehainam1973@gmail.com',
                'fb_url' => '',
                'company_website' => 'www.betongsonghong.com.vn',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Văn Ninh',
                'last_name' => 'Vũ',
                'mobile' =>'0902883862',
                'company_name' => 'Công ty cổ phần hội quán bất động sản',
                'position' =>'',
                'career' => 'Kinh doanh dịch vụ bất động sản',
                'email' =>'Hotinhlang@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Hoang Yen',
                'last_name' => 'Pham',
                'mobile' =>'0949229986',
                'company_name' => 'Công ty cp xuất nhập khẩu và đầu tư công nghệ cao kbf_ japan',
                'position' =>'',
                'career' => 'Nông nghiệp- siêu thị- nhà hàng',
                'email' =>'Yennykbf.japan@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Văn Thưởng',
                'last_name' => 'Vũ',
                'mobile' =>'0988846239',
                'company_name' => 'TVN ViNa',
                'position' =>'',
                'career' => 'Quảng Cáo',
                'email' =>'Hoangthuong186@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Văn Trung',
                'last_name' => 'Nguyễn',
                'mobile' =>'0968666615',
                'company_name' => 'Công ty Cổ phần Đầu tư xây dựng Kiên Hùng',
                'position' =>'',
                'career' => 'Xây dựng công trình dân dụng, giao thông, thủy lợi',
                'email' =>'vnkienhung.jsc@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Hữu Chính',
                'last_name' => 'Nguyễn',
                'mobile' =>'0988552299',
                'company_name' => 'Mỏ đá BMC Hoà Binh và nhà máy gạch bê tông BMC Việt Anh',
                'position' =>'',
                'career' => 'Khai thác chế biến đá xây dựng và sản xuất gạch không nung (bê tông cốt liệu)',
                'email' =>'huuchinh2501@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Hữu Sự',
                'last_name' => 'Vũ',
                'mobile' =>'0903284066',
                'company_name' => 'Cty TNHH Đồng Phát',
                'position' =>'',
                'career' => 'Xây dựng hạ tầng, khai thác mỏ sét và mỏ cát',
                'email' =>'Vuhuusu121278@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thu Hiền',
                'last_name' => 'Nguyễn',
                'mobile' =>'0989911999',
                'company_name' => 'May Bắc Giang',
                'position' =>'',
                'career' => 'May mặc',
                'email' =>'Nguyenthuhienmit@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Phu Dinh',
                'last_name' => 'Nguyen',
                'mobile' =>'0976361007',
                'company_name' => 'quang cao XUAN DINH',
                'position' =>'',
                'career' => 'QUANG CAO',
                'email' =>'Dinhqchn@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Chí Chung',
                'last_name' => 'Trần',
                'mobile' =>'0969566671',
                'company_name' => 'Công ty TNHH Thương mại và Du Lịch Ngọc Thảo',
                'position' =>'',
                'career' =>'Khách sạn',
                'email' =>'Ksbinhminh84nk@gmail.com',
                'fb_url' => '',
                'company_website' => 'binhminhngockhanh.com',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Văn Sỹ',
                'last_name' => 'Tạ',
                'mobile' =>'0916016820',
                'company_name' => 'Ct tnhhmtv sỹ thuỷ phát',
                'position' =>'',
                'career' => 'Sx tm vận tải',
                'email' =>'Tasythuy@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Văn Chinh',
                'last_name' => 'Đỗ',
                'mobile' =>'0985656359',
                'company_name' => 'Mactech Viet Nam',
                'position' =>'',
                'career' => 'Máy sấy nhiệt, Máy sấy lạnh, Máy ấp trứng gia cầm',
                'email' =>'vanchinhk12@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Hậu',
                'last_name' => 'Phan',
                'mobile' =>'0987672007',
                'company_name' => 'T-home',
                'position' =>'',
                'career' => 'Thiết kế thi công',
                'email' =>'Phanhau.spb@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Van Hai',
                'last_name' => 'Đào',
                'mobile' =>'0983174246',
                'company_name' => 'cong ty co phan che bien nong san doxaco',
                'position' =>'',
                'career' => 'che bien nong san',
                'email' =>'haidoxaco@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Chí Thiện',
                'last_name' => 'Nguyễn',
                'mobile' =>'0977956699',
                'company_name' => 'Công ty CP Kiến trúc Đông Á',
                'position' =>'',
                'career' => 'Tư vấn thiết kế, thi công: Kiến trúc, nội ngoại thất, cơ điện-công trình dân dụng&công nghiệp.',
                'email' =>'KientrucxdDongA@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Văn Khiếu',
                'last_name' => 'Ngô',
                'mobile' =>'0988558989',
                'company_name' => 'Tiệm Bánh IT',
                'position' =>'Giám đốc',
                'career' => 'Sản xuất bánh kem, bánh sinh nhật, bánh tiệc ngọt',
                'email' =>'Khieutnc@gmail.com',
                'fb_url' => '',
                'company_website' => 'http://banhsinhnhatngon.vn',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Hữu Thanh',
                'last_name' => 'Nguyễn',
                'mobile' =>'0979463666',
                'company_name' => 'Công ty CP Xây dựng và Thương mại Thái Dương',
                'position' =>'',
                'career' => '1. Xây dựng Cầu đường, hạ tầng khu Công nghiệp, khu du lịch',
                'email' =>'Thanhthaiduongjsc@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Huy Hoàng',
                'last_name' => 'Khúc',
                'mobile' =>'0973275761',
                'company_name' => 'Chỗ mình là đơn vị sự nghiệp của nhà nước, hiện chưa có cty',
                'position' =>'',
                'career' => 'Tổ chức sản xuất thực phẩm sạch',
                'email' =>'Hoangkhuc81@gmal.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thành Long',
                'last_name' => 'Nguyễn',
                'mobile' =>'0972479637',
                'company_name' => 'Công ty cổ phần More House',
                'position' =>'',
                'career' => 'Nội ngoại thất',
                'email' =>'CongtycophanMorehouse@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Doãn Hoàng Minh',
                'last_name' => 'Nguyễn',
                'mobile' =>'0982971998',
                'company_name' => 'Công ty cổ phần đàu tư phát triển hạ tầng đô thị việt nam',
                'position' =>'',
                'career' => 'Tư vấn và xây dựng',
                'email' =>'Hoangminhauc@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'văn Hải',
                'last_name' => 'Lê',
                'mobile' =>'0979919445',
                'company_name' => 'Trung Tâm Cơ Khí Trung Hải',
                'position' =>'',
                'career' => 'Cơ khí tổng hợp',
                'email' =>'Cktrunghai@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Xuân Trường',
                'last_name' => 'Trần',
                'mobile' =>'0904708434',
                'company_name' => 'Công ty thiết bị an ninh Trường Phát',
                'position' =>'Giám đốc',
                'career' => 'Thiết bị an ninh , giám sát , báo động',
                'email' =>'Baphong2012@gmail.com',
                'fb_url' => '',
                'company_website' => 'giamsatvn.vn',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Tuấn Anh',
                'last_name' => 'Tạ',
                'mobile' =>'0943612368/0983802868',
                'company_name' => 'Công ty cổ phần sông Hồng số 6',
                'position' =>'Tổng giám đốc',
                'career' => 'Xây dựng',
                'email' =>'Tuananhsonghong36@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thị Hồng Nga',
                'last_name' => 'Phan',
                'mobile' =>'0949760388',
                'company_name' => 'Ước mơ Việt',
                'position' =>'Lãnh đạo ước mơ Việt Quảng Ninh',
                'career' => 'Bảo trì điện tử điện lạnh',
                'email' =>'phanthihongngaqn@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Văn An',
                'last_name' => 'Đặng',
                'mobile' =>'0946875110',
                'company_name' => 'Cây xanh Nam Điền',
                'position' =>'Nhân viên kinh doanh',
                'career' => 'Cây cảnh',
                'email' =>'dangan326426@gmail.com',
                'fb_url' => '',
                'company_website' => 'Cayvanphonghanoi.com',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Văn Thạch',
                'last_name' => 'Phan',
                'mobile' =>'0974239137',
                'company_name' => 'Công ty TNHH Cây Xanh Nam Điền',
                'position' =>'Chuyên viên kinh doanh',
                'career' => 'Cung cấp , hoàn thiện cây xanh , không gian xanh ',
                'email' =>'namdien4990@gmail.com',
                'fb_url' => '',
                'company_website' => 'Cayxanhnamdien.com',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Văn Thạo',
                'last_name' => 'Dương',
                'mobile' =>'0912826686',
                'company_name' => '',
                'position' =>'',
                'career' => '',
                'email' =>'akido2016@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thuyên',
                'last_name' => 'Chu',
                'mobile' =>'0912322270',
                'company_name' => 'Công ty cổ phần đầu tư và phát triển TDT',
                'position' =>'Chủ tịch HĐQT',
                'career' => 'May mặc xuất khẩu',
                'email' =>'Chuthuyen@tdtgroup.vn',
                'fb_url' => '',
                'company_website' => 'www.tdtgroup.vn',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Việt Thắng',
                'last_name' => 'Nguyễn',
                'mobile' =>'0989539088',
                'company_name' => 'Công ty cổ phần đầu tư và phát triển TDT',
                'position' =>'Giám đốc',
                'career' => 'Sản xuát hàng may sẵn',
                'email' =>'thangnv.sm@gmail.com',
                'fb_url' => '',
                'company_website' => 'www.tdtgroup.vn',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Anh Tuấn',
                'last_name' => 'Nguyễn',
                'mobile' =>'0917244888',
                'company_name' => 'Công ty cổ phần dược phẩm Tây Á',
                'position' =>'Chủ tịch',
                'career' => 'Dược',
                'email' =>'tranfushico@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thị Kim Phụng',
                'last_name' => 'Vũ',
                'mobile' =>'0973522929',
                'company_name' => '',
                'position' =>'',
                'career' => '',
                'email' =>'',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Văn Hoàng',
                'last_name' => 'Hà',
                'mobile' =>'0943998988',
                'company_name' => 'Thiết bị nhà bếp Tân Hoàng Minh',
                'position' =>'',
                'career' => 'Kinh doanh thiết bị nhà bếp',
                'email' =>'',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Hà Hưng',
                'last_name' => 'Ma',
                'mobile' =>'0978661497',
                'company_name' => '',
                'position' =>'',
                'career' => '',
                'email' =>'',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thiều Quang',
                'last_name' => 'Phạm',
                'mobile' =>'0983563111',
                'company_name' => '',
                'position' =>'',
                'career' => '',
                'email' =>'',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thị Thu Hà',
                'last_name' => 'Đinh',
                'mobile' =>'0916026027',
                'company_name' => '',
                'position' =>'',
                'career' => '',
                'email' =>'',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Minh Phương',
                'last_name' => 'Tạ',
                'mobile' =>'0919269229',
                'company_name' => '',
                'position' =>'',
                'career' => '',
                'email' =>'',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Đức Dũng',
                'last_name' => 'Khuất',
                'mobile' =>'0904636377',
                'company_name' => '',
                'position' =>'',
                'career' => '',
                'email' =>'',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thị Xuyến',
                'last_name' => 'Nguyễn',
                'mobile' =>'0967596167',
                'company_name' => '',
                'position' =>'',
                'career' => '',
                'email' =>'',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>' Quang Đại',
                'last_name' => 'Lê',
                'mobile' =>'0981352388',
                'company_name' => '',
                'position' =>'',
                'career' => '',
                'email' =>'',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Việt Thắng',
                'last_name' => 'Nguyễn',
                'mobile' =>'0912781102',
                'company_name' => '',
                'position' =>'',
                'career' => '',
                'email' =>'',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thanh',
                'last_name' => 'Nguyễn',
                'mobile' =>'0983075548',
                'company_name' => '',
                'position' =>'',
                'career' => '',
                'email' =>'',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Văn Hiếu',
                'last_name' => 'Nguyễn',
                'mobile' =>'0987969237',
                'company_name' => '',
                'position' =>'',
                'career' => '',
                'email' =>'',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Yến Phượng',
                'last_name' => 'Phạm',
                'mobile' =>'0919025688',
                'company_name' => '',
                'position' =>'',
                'career' => '',
                'email' =>'',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Ngọc San',
                'last_name' => 'Đào',
                'mobile' =>'0973442036',
                'company_name' => '',
                'position' =>'',
                'career' => '',
                'email' =>'',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Đức Lực',
                'last_name' => 'Nguyễn',
                'mobile' =>'0966159739',
                'company_name' => '',
                'position' =>'',
                'career' => '',
                'email' =>'',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Ngọc Tú',
                'last_name' => 'Nguyễn',
                'mobile' =>'0969248666',
                'company_name' => '',
                'position' =>'',
                'career' => '',
                'email' =>'',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>' Minh Đức',
                'last_name' => 'Lê',
                'mobile' =>'0912343485',
                'company_name' => '',
                'position' =>'',
                'career' => '',
                'email' =>'',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],

       ];
        foreach ($data as $item){
            $item['password'] = '123456';
            $user = Sentinel::registerAndActivate($item);
            $role = Sentinel::findRoleBySlug('member');
            $role->users()->attach($user);
        }
    }
}