<?php

use Illuminate\Database\Seeder;

class MemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'first_name' =>'Tuấn Trung',
                'last_name' => 'Bùi',
                'mobile' =>'0934590969',
                'company_name' => 'Co-Well',
                'position' =>'Trưởng phòng',
                'career' => 'Công nghệ thông tin/viễn thông',
                'email' =>'trung.bui@co-well.vn',
                'fb_url' => '',
                'company_website' => 'co-well.vn',
                'bio' =>'',
                'security_question1' =>'20',
                'security_question2' => 'hiển',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Vũ Hiển',
                'last_name' => 'Nguyễn',
                'mobile' =>'0904001098',
                'company_name' => 'Co-well Châu Á',
                'position' =>'Giám đốc',
                'career' => 'Công nghệ thông tin/viễn thông',
                'email' =>'nguyenvuhien@gmail.com',
                'fb_url' => '',
                'company_website' => 'co-well.vn',
                'bio' =>'',
                'security_question1' =>'18-19/6/2016',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thị Hồng Hải',
                'last_name' => 'Nguyễn',
                'mobile' =>'0904904623',
                'company_name' => 'Công ty cổ phần Davicorp việt nam',
                'position' =>'Ceo',
                'career' => 'Thực phẩm',
                'email' =>'Nguyenhai2508@gmail.com',
                'fb_url' => '',
                'company_website' => 'Davicorp.vn',
                'bio' =>'',
                'security_question1' =>'18/6',
                'security_question2' => 'Thạch',
                'wanted' => 'Giao lưu hợp tác kết bạn',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Văn Quang',
                'last_name' => 'Vũ',
                'mobile' =>'0969672828',
                'company_name' => 'Trung tâm thiết kế và thi công nội thất KTV',
                'position' =>'Phụ trách trung tâm',
                'career' => 'Nội thất',
                'email' =>'quanghopphat@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18/6',
                'security_question2' => 'Thạch',
                'wanted' => 'Giao lưu - kết nối - chia sẻ',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thế Trường',
                'last_name' => 'Thân',
                'mobile' =>'0912440744',
                'company_name' => 'Trường Tiểu học Thượng Lan,Việt Yên, Bắc Giang',
                'position' =>'Hiệu trưởng ',
                'career' => 'Giáo dục, đào tạo',
                'email' =>'Truongthethan@gmail.com',
                'fb_url' => 'http://www.facebook.com/truong.thethan',
                'company_website' => 'ththuonglan.vietyen.edu.vn',
                'bio' =>'',
                'security_question1' =>'18/6',
                'security_question2' => 'Thạch',
                'wanted' => 'Giao lưu -chia sẻ -Học hỏi -Hợp tác ',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Văn Hồng',
                'last_name' => 'Đỗ',
                'mobile' =>'0932343937 /0974389185',
                'company_name' => 'Công ty cổ phần đầu tư thương mại và dịch vụ ihome việt nam',
                'position' =>'Giám đốc',
                'career' => 'Điện tử/Điện máy',
                'email' =>'hongdv@ihomevietnam.vn',
                'fb_url' => '',
                'company_website' => 'ihomevietnam.vn',
                'bio' =>'Là người có trách nhiệm với bản thân , công việc và các mối quan hệ...',
                'security_question1' =>'18/06/2016',
                'security_question2' => 'Thạch',
                'wanted' => 'Tình bằng hữu luôn là điều ngọt ngào, là điều quý giá trong cuộc đời chứ không phải là cơ hội vụ lợi.',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thành Chung',
                'last_name' => 'Nguyễn',
                'mobile' =>'0965389222/0946488966/0961222111',
                'company_name' => 'Thế Giới Công Nghệ Bình Minh',
                'position' =>'Ceo',
                'career' => 'Phụ kiện và đồ chơi công nghệ',
                'email' =>'thegioicongnghebinhminh@gmail.com',
                'fb_url' => 'https://www.facebook.com/congnghebinhminh',
                'company_website' => 'http://congnghebinhminh.com/',
                'bio' =>'Chuyên sỉ lẻ SẠC DỰ PHÒNG, SẠC CÁP, TAI NGHE, CAMERA HÀNH TRÌNH, WIFI, THẺ NHỚ, USB, KÍNH CƯỜNG LỰC, ĐỒ CHƠI CÔNG NGHỆ, PHỤ KIỆN ĐIỆN THOẠI, PHỤ KIỆN CNTT... Là đại lý phân phối sản phẩm của các hãng PISEN, REMAX, HOCO, TITAN, NEWMEN!...',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Giao lưu - Hợp tác - Sẻ chia',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Văn Xuyên',
                'last_name' => 'Trần',
                'mobile' =>'0934281889/0943588636',
                'company_name' => 'Công ty TNHH thời trang và thương mại Bảo Chính',
                'position' =>'Giám đốc',
                'career' => 'Dệt may/Thời trang',
                'email' =>'baoxuyen580@gmail.com',
                'fb_url' => 'Xuyentran',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Giao lưu -tìm kiếm đối tác-sân chơi sinh hoạt bổ ích tạo được sự thoải mái và xả bớt đi gánh nặng công việc ',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Quang Hưng',
                'last_name' => 'Nguyễn',
                'mobile' =>'0988114284',
                'company_name' => 'Công ty TNHH xây dựng và phát triển môi trường Việt',
                'position' =>'Giám đốc',
                'career' => 'Xây dựng/Kiến trúc',
                'email' =>'moitruongviet.edc@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'Tư vấn thiết kế xây dựng hệ thống cấp thoát nước, cần xử lý nước sạch hay nước thải, thiết kế xd hãy alo tôi!',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Hội tụ - kết nối - chia sẻ',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thùy Linh',
                'last_name' => 'Nguyễn',
                'mobile' =>'0974127081',
                'company_name' => 'Cơ khí xây dựng phong phú',
                'position' =>'CEO',
                'career' => 'Xây dựng/Kiến trúc',
                'email' =>'Linhnhomkinh@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'Mình là con trai nhưng tên lại là con gái. Hơi kỹ tính trong công việc. ',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Muốn  Được Giao lưu voi những chủ doanh nghiệp khác. Giao lưu ngành nghề hợp tác cùng nhau phát triển ',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thị Huệ',
                'last_name' => 'Nguyễn',
                'mobile' =>'0914876927',
                'company_name' => 'Công ty TNHH Bắc Huệ',
                'position' =>'Giám đốc',
                'career' => 'Gạch ốp lát và thiết bị vệ sinh',
                'email' =>'bachuent@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thị Ngân Giang',
                'last_name' => 'Đinh',
                'mobile' =>'0972785910',
                'company_name' => 'Công ty tnhh sản xuất và thương mại tổng hợp wisewear design Viet Nam',
                'position' =>'Giám đốc',
                'career' => 'Dệt may/Thời trang',
                'email' =>'Giangwisewear@gmail.com',
                'fb_url' => 'Giang dinhthingan',
                'company_website' => 'Www.wisewearvn.com',
                'bio' =>'Sống để yêu người.',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' =>'Kết nối. Sẻ chia',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thị Mai Liên',
                'last_name' => 'Lê',
                'mobile' =>'0912789415',
                'company_name' => 'Công ty cổ phần truyền thông AdsBNC Việt Nam',
                'position' =>'CEO',
                'career' => 'Truyền Thông/ Marketing tổng thể',
                'email' =>'lienltm@adsbnc.vn',
                'fb_url' => 'Lê Thị Mai Liên',
                'company_website' => 'adsbnc.vn',
                'bio' =>'Nếu mọi người gặp vấn đề về Marketing cho doanh nghiệp mình thì Tôi có thể giúp anh chị',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Mong muốn xây dựng thành một tổ chức chủ doanh nghiệp lớn mạnh đúng ý nghĩa, kết nối - sẻ chia - cùng lớn mạnh',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Minh Quốc',
                'last_name' => 'Bùi',
                'mobile' =>'0913377080',
                'company_name' => 'Công ty cổ phần sản xuất thương mại & dịch vụ Quốc Quốc',
                'position' =>'Chủ tịch HĐQT',
                'career' => 'Thi công công trình viễn thông /điều hoà và điện công nghiệp',
                'email' =>'quocquoc.jsc@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'Mình là Quốc đang công tác tại viễn thông Hưng yên phụ trách công tác kỹ thuật. Mình có thể tư vấn, thi công các công trình về viễn thông- cntt, lắp đặt bảo trì hệ thống điều hoà kể cả đh công nghiệp. Công trình điện công nghiệp. Rất mong được sự hợp tác, chia sẻ cùng các ace k34 - Giải phóng lãnh đạo',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Kết nối - chia sẻ - hợp tác',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thị Hương',
                'last_name' => 'Nguyễn',
                'mobile' =>'0902079688',
                'company_name' => 'Dolphin Seaair Service Corp',
                'position' =>'Trưởng đại diện Văn phòng Thái Nguyên',
                'career' => 'Vận tải quốc tế',
                'email' =>'Emily@dolphinseaair.com/ nguyenhuong83tn@gmail.com',
                'fb_url' => '0902079688',
                'company_website' => 'Www.dolphinseaair.com',
                'bio' =>'',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Đình Quảng',
                'last_name' => 'Dương',
                'mobile' =>'0913051857',
                'company_name' => 'Cty CP Gạch Không Nung BN',
                'position' =>'Giám đốc',
                'career' => 'Xây dựng/Kiến trúc',
                'email' =>'quangrtdh@gmail.com',
                'fb_url' => 'Dương Đình Quảng',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Hữu Phách',
                'last_name' => 'Đặng',
                'mobile' =>'0913525427/0987102575',
                'company_name' => 'Công ty TNHH PTNN Sinh thái Phú Thắng',
                'position' =>'Chủ tịch HĐQT',
                'career' => 'Phát triển trang trại sinh thái/sản xuất thực phẩm ATVSTP',
                'email' =>'danghuuphach@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'Cá nhân: 18 năm liên tục hoạt động lĩnh vực sx chăn nuôi, xây dựng trang trại, qui mô khảo sát đã vận hành 2400 heo nái.
DN: tổ chức sx 1200 heo nái; 5000 heo thương phẩm; 40.000 gà thả vườn; 1500 cây ổi lê; 1600 cây bưởi ; 1500 cây chanh.
Sản phẩm hàng Việt nam tin dùng 2016
Cam kết: Đảm bảo ATVSTP.
Sẵn sằng chia sẻ kinh nghiệm vơi 34',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Kết nối - Hội tụ- Chia sẻ- Giao lưu- tìm kiếm cơ hội hợp tác cùng phát triển.',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Danh Trung',
                'last_name' => 'Nguyễn',
                'mobile' =>'0916662810 / 0988461919',
                'company_name' => 'Công ty TNHH Quốc tế Trường Phúc',
                'position' =>'CEO',
                'career' => 'Xây dựng/Kiến trúc',
                'email' =>'trungnguyenfreeman@gmail.com',
                'fb_url' => '',
                'company_website' => 'Baochayvietnam.com.vn',
                'bio' =>'Hoà đồng, năng động, vui vẻ.',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Kết nối bạn bè, mở rộng mối quan hệ',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thị Minh Huyền',
                'last_name' => 'Nguyễn',
                'mobile' =>'0984789701, 0968571889',
                'company_name' => 'Cty TNHH MTV 1889',
                'position' =>'Giám đốc',
                'career' => 'Dệt may/Thời trang',
                'email' =>'minhhuyen1889@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Mở rộng mối quan hệ, hỗ trợ chéo...',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thuý Hằng',
                'last_name' => 'Phùng',
                'mobile' =>'0983005782',
                'company_name' => 'ADCOM',
                'position' =>'Phó Giám đốc',
                'career' => 'Tư vấn hỗ trợ kỹ thuật thực hiện dự án vốn phát triển ODA',
                'email' =>'Hangpt@adcom.vn/thuyhang.media@gmail.com',
                'fb_url' => 'Hang Fullmoon',
                'company_website' => 'adcom-add.vn',
                'bio' =>'',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => '',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Xuân Hải',
                'last_name' => 'Nguyễn',
                'mobile' =>'0912049268',
                'company_name' => 'Công ty TNHH Cây Xanh Nam Điền',
                'position' =>'Giám đốc',
                'career' => 'Xây dựng/Kiến trúc',
                'email' =>'Cayvanphonghanoi@gmail.com',
                'fb_url' => '',
                'company_website' => 'Cayxanhnamdien.com',
                'bio' =>'',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Hợp tác thành công',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thị Siêm',
                'last_name' => 'Nguyễn',
                'mobile' =>'0986111666',
                'company_name' => 'Dệt may Nga Xiêm',
                'position' =>'CEO',
                'career' => 'Dệt may/Thời trang',
                'email' =>'ntsiem@gmail.com',
                'fb_url' => 'Siem nguyen',
                'company_website' => '',
                'bio' =>'Dệt may Nga Xiêm chuyên cắt may và dệt (len) các loại quần áo thời trang; phân phối quần áo trẻ em với số lượng lớn; in chuyển nhiệt chất lượng cao trên vải cả cây và bán thành phẩm; nhận thêu số lượng lớn trên thành phẩm và bán thành phẩm.',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Mong muốn được trao đổi, học hỏi kinh nghiệm với các đơn vị khác, đồng thời mong muốn được mở rộng hợp tác với các đối tác trên cơ sở hai bên cùng có lợi',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thị Hà',
                'last_name' => 'Trần',
                'mobile' =>'0972988019',
                'company_name' => 'CÔNG TY CỔ PHẦN CÔNG NGHỆ SINH HỌC ANYOY VIỆT NAM',
                'position' =>'Trưởng phòng',
                'career' => 'Thức ăn chăn nuôi',
                'email' =>'thuhaktp@gmail.com',
                'fb_url' => 'thuhaktp',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Kết nối, giao lưu, học hỏi, chia sẻ, tìm đối tác.',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Huy Dũng',
                'last_name' => 'Nguyễn',
                'mobile' =>'0987613826',
                'company_name' => 'Grando - Shop giày dép nam',
                'position' =>'Chủ shop',
                'career' => 'Dệt may/Thời trang',
                'email' =>'huydunggtvt@gmail.com',
                'fb_url' => 'https://www.facebook.com/DungGiayGrando',
                'company_website' => '',
                'bio' =>'Em sinh năm 1992, hiện tại đang bán giày dep da, và muốn phát triển bản thân theo con đường kinh doanh, rất mong được giao lưu và học hỏi từ các anh các chị ạ',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Em muốn được giao lưu, học hỏi thêm với các anh chị.các chủ doanh nghiệp đi trước có nhiều kinh nghiệm ạ',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Xuân Ngọc',
                'last_name' => 'Nguyễn',
                'mobile' =>'0904921858',
                'company_name' => 'Công ty TNHH Sản Xuất Thiết Bị Công Nghiệp Việt Nam',
                'position' =>'Giám đốc',
                'career' => 'Máy móc/thiết bị',
                'email' =>'ngocvinpro@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Được học hỏi và giao lưu',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Hồng Tươi',
                'last_name' => 'Phạm',
                'mobile' =>'0969331183',
                'company_name' => 'Công ty TNHH Công nghệ kỹ thuật Bình An',
                'position' =>'Giám đốc',
                'career' => 'Điện tử/điện thoại/ viễn thông',
                'email' =>'elinkvietnam.vn@gmail.com',
                'fb_url' => '',
                'company_website' => 'www.elink.vn',
                'bio' =>'Rõ ràng tạo sức mạnh-chân thành để đi lên',
                'security_question1' =>'Quên',
                'security_question2' => 'Thạch',
                'wanted' => 'Hợp tác, chia sẻ',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Xuân Trường',
                'last_name' => 'Trương',
                'mobile' =>'0979754331',
                'company_name' => 'Công ty TNHH Thẩm Mỹ Bác Sĩ Điền',
                'position' =>'Phó Giám Đốc Điều Hành',
                'career' => 'Thẩm mỹ / Làm đẹp',
                'email' =>'truongtx.bsdien@gmail.com',
                'fb_url' => 'https://www.facebook.com/trg2610',
                'company_website' => 'bsdien.com',
                'bio' =>'Là một trong những công ty trẻ nhưng năng lực và bộ máy chuyên nghiệp, nhiệt huyết. Đẩy mạnh Marketing Online thúc đẩy tiềm lực lợi thế từ các công cụ mạng. Kết hợp hợp tác với bệnh viện nhằm tạo ra môi trường chuyên nghiệp.',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Kết nối giao lưu, học hỏi kinh nghiệm, hợp tác win - win',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Đức Quang',
                'last_name' => 'Vũ',
                'mobile' =>'0988087868',
                'company_name' => 'Công ty CP Phát Triển Dịch Vụ Bàn Tay Vàng (Goldenhands.,dsc)',
                'position' =>'CEO',
                'career' => 'Dịch vụ giúp việc chuyên nghiệp',
                'email' =>'info.vquang@gmail.com',
                'fb_url' => 'Rô Củ Từ',
                'company_website' => 'cangiupviec.vn',
                'bio' =>'',
                'security_question1' =>'02/07/2016',
                'security_question2' => 'Kiếm Phong',
                'wanted' => 'CLBdoanh nhân sẽ là nơi giao lưu, gắn kết các thành viên vì mục đích chung, chia sẻ những thành công, thất bại, giúp đỡ nhau cùng phát triển.',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Phạm Bình',
                'last_name' => 'Trần',
                'mobile' =>'0918606689',
                'company_name' => 'Công ty cổ phần đầu tư và thương mại Sinh Phúc',
                'position' =>'Chủ tịch HĐQT',
                'career' => 'Dệt may/Thời trang',
                'email' =>'binhjuki@yahoo.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'Kinh doanh dệt may 15 năm - Hiện nay làm KD Amway',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Mở rông hợp tác',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Ngọc Thoan',
                'last_name' => 'Trần',
                'mobile' =>'0965362819',
                'company_name' => 'Công ty TNHH Đầu Tư Phát Triển Việt Lạc',
                'position' =>'Giám đốc',
                'career' => 'Công nghệ thông tin/viễn thông',
                'email' =>'thoan@vietlac.com',
                'fb_url' => 'https://www.facebook.com/vietlac.thoan',
                'company_website' => 'http://vietlac.com',
                'bio' =>'Yêu công nghệ, thích đọc sách, thích giúp đỡ hỗ trợ người khác',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Giao lưu, chia sẻ, học hỏi',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thị Minh Hà',
                'last_name' => 'Đặng',
                'mobile' =>'0986492868',
                'company_name' => 'Công ty cp trúc quang',
                'position' =>'Trưởng phòng',
                'career' => 'Dệt may/Thời trang',
                'email' =>'Minhha@trucquang.com',
                'fb_url' => '',
                'company_website' => 'Kisetsu.com.vn',
                'bio' =>'',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Kết nối - chia sẻ đê cùng nhau thành công :)',
                'share' => '0',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Thanh Điệp',
                'last_name' => 'Đinh',
                'mobile' =>'0975278687/01678788888',
                'company_name' => 'Công Ty Cổ Phần Đầu Tư Quốc Tế Thiên Hương',
                'position' =>'CEO',
                'career' => 'Dệt may/Thời trang',
                'email' =>'thienhuong9316@gmail.com',
                'fb_url' => 'Thienhuongshoes',
                'company_website' => 'Thienhuongshoes.vn',
                'bio' =>'Công ty cổ phần đầu tư quốc tế Thiên Hương. Là đơn vị Sản xuất kinh doanh phân phối các sản phẩm giày dép công sở, thời trang. Công ty rất mong muốn được giao lưu hợp tác và chia sẻ với tất cả các anh chị, các đối tác bán buôn bán sỉ, bán lẻ giày dép, kể cả các nghành hàng thời trang trên toàn quốc. Các anh chị nào đang kinh doanh, có người thân đang kinh doanh, hoặc có máu kinh doanh hãy liên hệ trực tiếp với tôi để nhận được sự hợp tác tốt nhất. (Mr Điệp: 0975278687). Trâm trọng cảm ơn!!!',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Tôi muốn  được kết nối  để học hỏi, giao lưu, chia sẻ và trải nghiệm với tất cả mọi người.',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],
            [
                'first_name' =>'Vũ Nam',
                'last_name' => 'Lương',
                'mobile' =>'0983165020',
                'company_name' => 'TNHH HD Việt Nam',
                'position' =>'Phó Giám Đốc',
                'career' => 'Công nghệ thông tin/viễn thông',
                'email' =>'luongvunam@gmail.com',
                'fb_url' => '',
                'company_website' => '',
                'bio' =>'Chuyên về phần mềm, thiết bị, tích hợp hệ thống cho các đài truyền hình, công ty sản xuất media',
                'security_question1' =>'18-6',
                'security_question2' => 'Thạch',
                'wanted' => 'Giao lưu trao đổi kinh nghiệm, tìm kiếm cơ hội hợp tác phát triển',
                'share' => '1',
                'permissions' => ['member'=> true]
            ],

        ];
        foreach ($data as $item){
           $item['password'] = $item['email'] . '123';
            $user = Sentinel::registerAndActivate($item);
            $role = Sentinel::findRoleBySlug('member');
            $role->users()->attach($user);
        }
    }
}
